In [1]:
import numpy as np

#### Numpy Datatypes / dtypes
In the numeric form, four data types are possible
- int32
- int64
- float32
- float64

Use .astype() function to type cast <br>
Use .dtype on an np array to get the type of elements in the array <br>
If one string, is used in the array, all elements are coerced into strings<br>
If one float is used in the array, all elemets are coerced into floats


 #### Creating a numpy array from list, list of lists

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]]);x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Creating a array of integers from one to 10

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Generating random nd array

In [8]:
# generating a nd-array of random numbers with 3 rows and 4 columns
np.random.random((2,5))

array([[0.97104887, 0.50727521, 0.07962171, 0.31907576, 0.11345996],
       [0.2324218 , 0.21983954, 0.00270716, 0.9239283 , 0.65143037]])

 #### Flattening an array

In [14]:
f = x.flatten();f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Reshaping an numpy array

In [16]:
reshaped_array = f.reshape(2,5);reshaped_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
np.zeros((3,2),dtype=np.int32)

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [21]:
np.array([1.2,True],dtype=np.int8)

array([1, 1], dtype=int8)